name: shakespeare
version: 0.1.0

dependencies:
- aeson
- base
- bytestring
- containers
- formatting
- generic-lens
- lens
- roman-numerals
- text

ghc-options:
- -Wall
- -Werror

library:
  source-dirs: source

executables:
  hamlet:
    source-dirs: app
    main: Hamlet.hs
    other-modules: []
    dependencies:
    - shakespeare
  auth:
    source-dirs: app
    main: Auth.hs
    other-modules: []
    dependencies:
    - authenticate-oauth
    - twitter-conduit
  post-tweets:
    source-dirs: app
    main: PostTweets.hs
    other-modules: []
    dependencies:
    - logging
    - shakespeare
    - twitter-conduit
    - twitter-types

tests:
  hamlet-test:
    source-dirs: test
    main: HamletTest.hs
    other-modules: []
    dependencies:
    - Diff
    - hedgehog
    - shakespeare
