name: shakespeare
version: 0.1.0

dependencies:
- base
- containers
- text

ghc-options:
- -Wall
- -Werror

executables:
  hamlet:
    source-dirs: source
    main: Hamlet.hs
    other-modules: []
  auth:
    source-dirs: source
    main: Auth.hs
    other-modules: []
    dependencies:
    - authenticate-oauth
    - bytestring
    - twitter-conduit
