name: shakespeare
version: 0.1.0

dependencies:
- base
- containers
- formatting
- text

ghc-options:
- -Wall
- -Werror

library:
  source-dirs: source

executables:
  hamlet:
    source-dirs: app
    main: Hamlet.hs
    other-modules: []
    dependencies:
    - shakespeare
  auth:
    source-dirs: app
    main: Auth.hs
    other-modules: []
    dependencies:
    - authenticate-oauth
    - bytestring
    - twitter-conduit
