resolver: lts-11.14
extra-deps:
- aeson-1.3.1.1
- cereal-0.5.3.0
- chatter-0.9.1.0
- conduit-1.2.13.1
- conduit-extra-1.2.3.2
- fullstop-0.1.4
- http-conduit-2.2.4
- logging-3.0.5
- pdf-toolbox-content-0.0.5.1
- pdf-toolbox-core-0.0.4.1
- pdf-toolbox-document-0.0.7.1
- resourcet-1.1.11
- roman-numerals-0.5.1.5
- tokenize-0.3.0
- twitter-conduit-0.2.3
- twitter-types-0.7.2.2
- twitter-types-lens-0.7.2
